#!/usr/bin/env bash

cd "$(dirname "$0")"
source ./ver
rm ./client

echo "Building client (Linux)..."
go build ./cmd/client || exit 1

echo Copying client and config...
cp ./client_config.toml $DEST_DIR/client_config.toml || exit 1
cp ./client $DEST_DIR/MasterDnsVPN_Client_Linux_$DEPLOY_VER || exit 1
