#!/usr/bin/env bash

cd "$(dirname "$0")"

pkill -fi masterdnsvpn -9

./prep_cli_linux || exit 1

source ./ver

echo "Running linux cli (cmdln)..."
(cd $DEST_DIR && ./MasterDnsVPN_Client_Linux_$SERVER_EXEC_VER -config "./${CLI_CONFIG_DEPLOYED}.toml" -resolvers "./$DEFAULT_RESOLVERS_FILE")
