#!/usr/bin/env bash

source ./ver

cd "$(dirname "$0")"
rm ./server
go build ./cmd/server || exit 1
echo Deploy...

rm ./$SERVICE_BIN
ln -s ./server ./$SERVICE_BIN

ssh -T $SERVER_NAME << EOF || exit 1
  echo MDV Server: Stopping $SERVICE_NAME
  systemctl stop $SERVICE_NAME
EOF

echo Copying server and config to $SERVICE_DIR...
rsync -avzL --progress ./$SERVICE_BIN ./server_config.toml $SERVER_NAME:$SERVICE_DIR/  || exit 1

ssh -T $SERVER_NAME << EOF
  echo MDV Server: Starting $SERVICE_NAME
  systemctl restart $SERVICE_NAME
  journalctl -fu $SERVICE_NAME
EOF

