#!/usr/bin/env bash

cd "$(dirname "$0")"

pkill -fi masterdnsvpn -9

./prep_cli_linux || exit 1

source ./ver

echo Running linux cli...
(cd $DEST_DIR && "./MasterDnsVPN_Client_Linux_$SERVER_EXEC_VER")
