#!/usr/bin/env bash

#SERVER_NAME=sewr3
SERVER_NAME=sewr4
SERVICE_NAME=masterdnsvpn4
SERVICE_DIR=/opt/masterdnsvpn4
SERVICE_BIN=mdvserver4

DEPLOY_VER=farvardin22

DEST_DIR=/mnt/c/Projects/denerastin/spr2x/MasterDnsVPN_Client

CLI_CONFIG_DEPLOYED=1_server4_${DEPLOY_VER}
